version: '3.8'

services:
  # Nginx webserver service
  nginx:
    image: nginx:1.18
    ports:
      - 80:80
      - 443:443
      - 8282:8282
    volumes:
      - ./src:/var/www/node114.webte.fei.stuba.sk/
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
      - ./.docker/nginx/ssl/certs:/etc/ssl/certs/
      - ./.docker/nginx/ssl/private:/etc/ssl/private/
    depends_on:
      - php

  # PHP-FPM service
  php:
    build: ./.docker/php
    working_dir: /var/www/node114.webte.fei.stuba.sk/
    volumes:
      - ./src:/var/www/node114.webte.fei.stuba.sk/
      - ./.docker/composer/vendor:/var/www/node114.webte.fei.stuba.sk/vendor
    environment:
      PHP_IDE_CONFIG: "serverName=node114.webte.fei.stuba.sk"
    depends_on:
      mysql:
        condition: service_healthy
      composer:
        condition: service_started
    command: sh -c "php ./socket/wsserver.php start -d && php-fpm"

  composer:
    image: composer/composer
    working_dir: /composer
    ports:
      - 9001:9000
    volumes:
      - ./.docker/composer:/composer
    command: install

  #MySQL service
  mysql:
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "Cv~my8!82ln("
      # MYSQL_ROOT_HOST: "%"
      MYSQL_USER: "Tim5"
      MYSQL_PASSWORD: "eN;D4H}4}Bt5"
      MYSQL_DATABASE: "final"
    volumes:
      - ./.docker/mysql/my.cnf:/etc/mysql/mysql.cnf
      - ./.database:/docker-entrypoint-initdb.d
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 10
  
  # phpMyAdmin interface
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy
# Volumes
volumes:
  mysqldata:
