const cookieAccepted = localStorage.getItem('cookieAccepted');
if (!cookieAccepted) {
    Swal.fire({
        title: 'Súhlas so súbormi cookie',
        html: 'Táto webová stránka používa súbory cookie na zabezpečenie toho, aby ste na našej webovej stránke získali najlepšie skúsenosti. Súbory cookie sú malé textové súbory, ktoré sú uložené vo vašom zariadení a pomáhajú poskytovať personalizovaný zážitok pri prehliadaní a analyzujú premávku na webovej stránke. Kliknutím na tlačidlo "Súhlasiť" súhlasíte s používaním všetkých súborov cookie.',
        icon: 'info',
        showCancelButton: true,
        confirmButtonText: 'Súhlasiť',
        cancelButtonText: 'Odmietnuť',
        allowOutsideClick: false,
        allowEscapeKey: false
    }).then((result) => {
        if (result.isConfirmed) {
            localStorage.setItem('cookieAccepted', true);
            Swal.fire({
                title: 'Súbor cookies bol úspešne akceptovaný!',
                icon: 'success',
                confirmButtonText: 'OK'
            });
        } else {
            window.location.href = 'restricted.php';
        }
    });
}


AOS.init();
particlesJS("particles-js", {
    "particles": {
        "number": {"value": 160, "density": {"enable": true, "value_area": 800}},
        "color": {"value": "#ffffff"},
        "shape": {
            "type": "circle",
            "stroke": {"width": 0, "color": "#000000"},
            "polygon": {"nb_sides": 5},
            "image": {"src": "img/github.svg", "width": 100, "height": 100}
        },
        "opacity": {
            "value": 0.5,
            "random": false,
            "anim": {"enable": false, "speed": 1, "opacity_min": 0.1, "sync": false}
        },
        "size": {
            "value": 3,
            "random": true,
            "anim": {"enable": false, "speed": 40, "size_min": 0.1, "sync": false}
        },
        "line_linked": {"enable": true, "distance": 150, "color": "#ffffff", "opacity": 0.4, "width": 1},
        "move": {
            "enable": true,
            "speed": 6,
            "direction": "none",
            "random": false,
            "straight": false,
            "out_mode": "out",
            "bounce": false,
            "attract": {"enable": false, "rotateX": 600, "rotateY": 1200}
        }
    },
    "interactivity": {
        "detect_on": "canvas",
        "events": {
            "onhover": {"enable": true, "mode": "repulse"},
            "onclick": {"enable": false, "mode": "push"},
            "resize": true
        },
        "modes": {
            "grab": {"distance": 400, "line_linked": {"opacity": 1}},
            "bubble": {"distance": 400, "size": 40, "duration": 2, "opacity": 8, "speed": 3},
            "repulse": {"distance": 63.86715631486508, "duration": 0.4},
            "push": {"particles_nb": 4},
            "remove": {"particles_nb": 2}
        }
    },
    "retina_detect": true
});

function translateToEnglish() {
    document.getElementById('pageTitle').innerText = 'ODILS |> Homepage';
    document.getElementById('homeLink').innerHTML = '<i class="fas fa-home"></i> Home';
    document.getElementById('loginLink').innerHTML = "<i class=\"fas fa-angle-double-right\"></i> Login";
    document.getElementById('navbarDropdown').innerHTML = '<i class="fas fa-globe"></i> Language';
    document.getElementById('invitationHeading').innerHTML = '👋 <strong>Hey, got an invitation code?</strong>';
    document.getElementById('logoutLink').innerHTML = '<i class="fas fa-sign-out-alt"></i> Logout';
    document.getElementById('invitationMessage').innerText = 'Enter the invitation code you received to connect as visitor';
    document.getElementById('connectText').innerText = 'Connect';
    document.getElementById('whatsGoodHeading').innerHTML = "🔍 <strong>WHAT IS ODILS?</strong>";
    document.getElementById('whatsGoodText1').innerHTML = '<strong>ODILS</strong> is an easy to use Q&A and polling platform for meetings and events. It allows meeting and event organizers to crowdsource top questions to drive meaningful conversations, engage participants with live polls and capture valuable event data.';
    document.getElementById('whatsGoodText2').innerHTML = 'Through <strong>ODILS</strong>, attendees transcend the role of mere spectators, becoming integral contributors to the discourse.';
    document.getElementById('needHelpText').innerText = 'Do you need help?';
    document.getElementById('documentationText').innerHTML = 'You can find our documentation here: <a href="https://www.example.com/documentation">DOCUMENTATION</a>';
    document.getElementById('logoText').innerText = 'The logo was created using';
    document.getElementById('phoneIconText').innerText = 'the phone icon is from';
    document.getElementById('aiText').innerText = 'and some parts of the text were generated by';
    document.getElementById('rightsReservedText').innerText = 'All rights reserved.';
    document.getElementById('schoolProjectText').innerText = 'This is a school project and is not affiliated with Cisco/Slido.';
    document.getElementById('englishIndicator').style.display = 'inline';
    document.getElementById('slovakIndicator').style.display = 'none';
    document.getElementById('invitationCode').placeholder = 'Enter your 6-digit code'
    localStorage.setItem('selectedLanguage', 'english');
    let credentials = sessionStorage.getItem('credentials');
    if (credentials) {
        let parsedCredentials = JSON.parse(credentials);
        let userNameLink = document.getElementById('userNameLink');
        userNameLink.innerHTML = "You are logged in as <strong>" + parsedCredentials.username + " </strong>";
    }
}

function translateToSlovak() {
    document.getElementById('pageTitle').innerText = 'ODILS |> Domov';
    document.getElementById('homeLink').innerHTML = '<i class="fas fa-home"></i> Domov';
    document.getElementById('loginLink').innerHTML = "<i class=\"fas fa-angle-double-right\"></i> Prihlásenie";
    document.getElementById('navbarDropdown').innerHTML = '<i class="fas fa-globe"></i> Jazyk';
    document.getElementById('invitationHeading').innerHTML = '👋 <strong>Ahoj, máš pozvánkový kód?</strong>';
    document.getElementById('logoutLink').innerHTML = '<i class="fas fa-sign-out-alt"></i> Odhlásenie';
    document.getElementById('invitationMessage').innerText = 'Zadaj pozvánkový kód, ktorý si dostal, aby si sa mohol pripojiť ako návštevník.';
    document.getElementById('connectText').innerText = 'Pripojiť sa';
    document.getElementById('whatsGoodHeading').innerHTML = "🔍 <strong>ČO JE ODILS?</strong>";
    document.getElementById('whatsGoodText1').innerHTML = '<strong>ODILS</strong> je jednoduchá a intuitívna platforma pre otázky a ankety, určená pre stretnutia a udalosti. Organizátorom stretnutí a podujatí umožňuje získať najlepšie otázky od účastníkov a viesť zmysluplné rozhovory, zapájať účastníkov živými anketami a zbierať cenné údaje o udalostiach.';
    document.getElementById('whatsGoodText2').innerHTML = 'Prostredníctvom <strong>ODILS</strong> účastníci presahujú úlohu iba divákov, stávajú sa neoddeliteľnými prispievateľmi k diskurzu.';
    document.getElementById('needHelpText').innerText = 'Potrebujete pomoc?';
    document.getElementById('documentationText').innerHTML = 'Nájdite našu dokumentáciu tu: <a href="https://www.example.com/documentation">DOKUMENTÁCIA</a>';
    document.getElementById('logoText').innerText = 'Logo bolo vytvorené pomocou';
    document.getElementById('phoneIconText').innerText = 'ikona telefónu je od';
    document.getElementById('aiText').innerText = 'a niektoré časti textu boli vygenerované pomocou';
    document.getElementById('rightsReservedText').innerText = 'Všetky práva vyhradené.';
    document.getElementById('schoolProjectText').innerText = 'Toto je školský projekt a nie je spätý s Cisco/Slido.';
    document.getElementById('slovakIndicator').style.display = 'inline';
    document.getElementById('englishIndicator').style.display = 'none';
    document.getElementById('invitationCode').placeholder = 'Zadaj tvôj 6 miestný kód'
    localStorage.setItem('selectedLanguage', 'slovak');
    let credentials = sessionStorage.getItem('credentials');
    if (credentials) {
        let parsedCredentials = JSON.parse(credentials);
        let userNameLink = document.getElementById('userNameLink');
        userNameLink.innerHTML = "Si prihlásený ako <strong>" + parsedCredentials.username + " </strong>";
    }
}